first attempt to run docker on CI

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -16,3 +16,15 @@ jobs:
     - uses: actions/checkout@v4
     - name: Build the Docker image
       run: docker compose build
+
+    - name: Run the Docker container
+      run: docker compose up --abort-on-container-exit
+
+    - name: Verify container exit code
+      run: |
+        if [ $? -ne 0 ]; then
+          echo "Container exited with errors."
+          exit 1
+        else
+          echo "Container ran successfully."
+        fi
